EN: null
TR:
  Balance: Bakiye
  Credit: Alacak
  Debit: Borç
  FirstName: Adı
  IsBlocked: Kullanım Dışı
  LastName: Soyadı
  SalesChannelCode: Satış Kanalı
  SalesChannelDescription: Satış Kanalı Açıklama
